
FROM resin/%%RESIN_MACHINE_NAME%%-node:0.10.22-onbuild

RUN DEBIAN_FRONTEND=noninteractive JOBS=MAX sudo npm config set registry http://registry.npmjs.org/ && npm install -ddd --unsafe-perm || cat /usr/src/app/npm-debug.log

COPY . /usr/src/app

#RUN ln -s /usr/src/app /app
CMD ["node", "index.js"]