
FROM resin/%%RESIN_MACHINE_NAME%%-node:0.10.22-onbuild

RUN apt-get install nodejs-legacy npm
RUN DEBIAN_FRONTEND=noninteractive JOBS=MAX npm install --verbose --unsafe-perm --build-from-source

COPY . /usr/src/app

#RUN ln -s /usr/src/app /app
CMD ["node", "index.js"]